### ISSUE TITLE
Tests not working with namespaced package

### ISSUE THREAD

**Issue by alexlafroscia** [kaliber5/ember-fastboot-addon-tests#1]
I'm trying to get this step up in my addon but am running into issues.  Here is the output:

```txt
> ember fastboot:test
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Running Fastboot tests! This may take a while...


  1) "before all" hook
  2) "after all" hook

  0 passing (2m)
  2 failing

  1)  "before all" hook:
    Error: ENOENT: no such file or directory, symlink '/Users/alexlafroscia/Code/nest/ember-wizard' -> '/var/folders/0q/39y8ksfj38j6ll8vxv1lf28c00c15m/T/d-11697-74375-jg2wkb/pristine/fastboot/node_modules/@alexlafroscia/ember-wizard'
      at Error (native)
      at Object.fs.symlinkSync (fs.js:897:18)
      at symlink (node_modules/ember-fastboot-addon-tests/node_modules/ember-cli-addon-tests/node_modules/symlink-or-copy/index.js:79:14)
      at symlinkOrCopySync (node_modules/ember-fastboot-addon-tests/node_modules/ember-cli-addon-tests/node_modules/symlink-or-copy/index.js:55:5)
      at module.exports (node_modules/ember-fastboot-addon-tests/node_modules/ember-cli-addon-tests/lib/utilities/symlink-directory.js:7:3)
      at node_modules/ember-fastboot-addon-tests/node_modules/ember-cli-addon-tests/lib/utilities/pristine.js:217:5
      at tryCatch (node_modules/ember-fastboot-addon-tests/node_modules/rsvp/dist/rsvp.js:538:12)
      at invokeCallback (node_modules/ember-fastboot-addon-tests/node_modules/rsvp/dist/rsvp.js:553:13)
      at publish (node_modules/ember-fastboot-addon-tests/node_modules/rsvp/dist/rsvp.js:521:7)
      at flush (node_modules/ember-fastboot-addon-tests/node_modules/rsvp/dist/rsvp.js:2373:5)

  2)  "after all" hook:
    Error: You must call `startServer()` before calling `stopServer()`.
      at AddonTestApp.stopServer (node_modules/ember-fastboot-addon-tests/node_modules/ember-cli-addon-tests/lib/models/addon-test-app.js:77:11)
at Context.<anonymous> (node_modules/ember-fastboot-addon-tests/lib/tests/setup.js:36:16)



2
```

The test setup is super basic:
- [Test file](https://github.com/alexlafroscia/ember-wizard/blob/240acb94ca0c0ef22de2c0d8d2ecf28b44abd1b4/fastboot-tests/index-test.js)
- [Template](https://github.com/alexlafroscia/ember-wizard/blob/240acb94ca0c0ef22de2c0d8d2ecf28b44abd1b4/fastboot-tests/fixtures/fastboot/app/templates/index.hbs)

You can find a branch of the repo, with the addon set up and installed, [here](https://github.com/alexlafroscia/ember-wizard/tree/add-fastboot-tests).

**Comment by simonihmig** [comment]
I checked out your branch, and got the same error. It comes from the upstream package [ember-cli-addon-tests](https://github.com/tomdale/ember-cli-addon-tests), which makes a new app and symlinks your addon into it. The symlink target is the app's ` node_modules/<packagename>` folder, with `<packagename>` taken from the addon's `package.json`.  Your scoped package name (https://github.com/alexlafroscia/ember-wizard/blob/add-fastboot-tests/package.json#L2) is rather unusual, but apparently valid (https://docs.npmjs.com/misc/scope). But this breaks the symlink step in ember-cli-addon-tests!

After changing the package name to just "ember-wizard", the error vanished!

Will try to fix this in ember-cli-addon-tests, in the meantime the only solution would be as described to use a plain package name...

**Comment by alexlafroscia** [comment]
Damn. Unfortunately `ember-wizard` is already taken, and the scoped name has been a lesson in which tools do and don't play nice with it!

Thanks for investigating, I appreciate the help!

**Comment by simonihmig** [comment]
@alexlafroscia Fixed this upstream in `ember-cli-addon-tests` with v0.4.1. After `rm -rf node_modules && npm i` you should have the new version, and this should fix the problem as it did for me: 

![image](https://cloud.githubusercontent.com/assets/1325249/19403706/452ca910-9269-11e6-9daf-4c3c3219f8d0.png)

Can you confirm?

**Comment by alexlafroscia** [comment]
Yup! Thanks so much for the help!

**Comment by alexlafroscia** [comment]
Additionally, I was happy to find out that you can use this directly with `ember-try` to run the Fastboot tests in a different job than other tests (just for efficiency's sake).  I saw you want to run against multiple Ember versions, but people should be able to configure that with `ember-try` already.

https://travis-ci.org/alexlafroscia/ember-wizard/jobs/167820899

**Comment by simonihmig** [comment]
Good to know, thanks!
