### ISSUE TITLE
Include package in installPackages option

### ISSUE THREAD

**Issue by c410-f3r** [kaliber5/ember-fastboot-addon-tests#12]
I am having a hard time trying to include the `ember-concurrency` package into the fastboot carousel test of `ember-bootstrap`.

```
setupTest('carousel', {
  installPackages: {
    'ember-concurrency': '0.8.7'
  }
});
```

The console output of `ember fastboot:serve` shows that the package could not be found.
`ember fastboot:test` fails with `Error: From should be a file or directory` and changing the setupTest name to `fastboot` also fails with `AssertionError` (element is not rendered).
Tried several strategies with no success, am I doing something wrong here?

**Comment by simonihmig** [comment]
@c410-f3r I am not sure about this error, would have to investigate. But as this is related to your PR for ember-bootstrap, I am wondering why you would need to install ember-concurrency. It should be specified as a dependency (not devDependency) of ember-bootstrap, so no need to manually install it!?

**Comment by c410-f3r** [comment]
You are right, it is not an `ember-fastboot-addon-tests` problem. Sorry for the lack of attention.

**Comment by simonihmig** [comment]
No problem at all!
