### ISSUE TITLE
Release to fix npm audit error

### ISSUE THREAD

**Issue by mansona** [kaliber5/ember-fastboot-addon-tests#25]
Howdy folks 👋 

I notice that you have updated mocha in this commit https://github.com/kaliber5/ember-fastboot-addon-tests/commit/f17a15625be300121b12e6b1c58358a84007052d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R67 but there hasn't been a release since that update 🤔 

Any chance we could get a release with just the latest dependecies? The reason I ask is because the current latest release give a critial security advisory to all git repos that depend on it. I know that the issue doesn't apply in the case that we're running it but I would very much like to get rid of those warnings 😂

**Comment by simonihmig** [comment]
@mansona thanks for reminding, seems I forgot about it... Published as 0.5.0!

**Comment by mansona** [comment]
thanks a million @simonihmig 🎉
