### ISSUE TITLE
Can this be used with normal apps?

### ISSUE THREAD

**Issue by t4t5** [kaliber5/ember-fastboot-addon-tests#4]
Sweet project!

I'm wondering if this can be used with "normal" Ember apps, and not just addons.

If not, do you plan on supporting it?

Cheers!

**Comment by simonihmig** [comment]
No, currently not. But I am in the need for a better solution for app testing right now, too. So I might come up with something similar to this one!

**Comment by simonihmig** [comment]
This is the companion addon for apps: https://github.com/kaliber5/ember-fastboot-app-tests
