### ISSUE TITLE
feature request: add a command to run the fastboot-tests app

### ISSUE THREAD

**Issue by bantic** [kaliber5/ember-fastboot-addon-tests#5]
It would simplify debugging test failures a lot if I could run the fastboot-tests app locally (in either fastboot or even non-fastboot) mode and poke around the app to make sure I'm writing my test selectors correctly.
<3 this project. Using it now for https://github.com/bustlelabs/ember-mobiledoc-dom-renderer

**Comment by simonihmig** [comment]
Thanks, good to see it is of some use for others as well! ;)

Shouldn't be too hard to accomplish. And I definitely see the value in that. Given the "speed" of the tests, debugging them is certainly no fun...

**Comment by simonihmig** [comment]
@bantic Added a `ember fastboot:serve` command and just released `0.3.0`, hope that covers your needs! :)
